configuration_form_simple:
  path: /mymodule/configuration
  methods: [GET, POST]
  controller: PrestaShop\Module\mymodule\Controller\ConfigurationController::index
  defaults:
    legacy_controller: AdminMyModule
    legacy_link: AdminMyModule
