services:
  _defaults:
    public: true

  # Demo configuration text form
  prestashop.module.mymodule.form.type.configuration_text:
    class: 'PrestaShop\Module\mymodule\Form\ConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  prestashop.module.mymodule.form.configuration_text_data_configuration:
    class: PrestaShop\Module\mymodule\Form\ConfigurationTextDataConfiguration
      arguments: ['@prestashop.adapter.legacy.configuration']  